name: Go Vulnerability Checker
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64-govuln-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.3"
      - run: date
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          echo "${TARGET}"
          case "${TARGET}" in
            linux-amd64-govuln-check)
              go install golang.org/x/vuln/cmd/govulncheck@latest
              govulncheck ./...
              ;;
          esac
